### ISSUE TITLE
Seeding Input: Duplicates appearing in Area Dropdown

### ISSUE THREAD

**Issue by braughtg** [dickinson-comp190/GitKit-FarmData2-Sp23#114]
The Area drop down in the Seeding Input form contains duplicates.  The same list of areas appears to be being appended to the dropdown multiple times.  Each Area should appear in this list only one time.

**Steps to Reproduce**
1. Clear browsing data
2. Visit Seeding Input form
  * Area's will be listed once.
3. Visit a different tab (e.g. info)
4. Area list will update with a second copy of all areas.
5. Each visits to another tab and return to the Seeding Input form will add another copy of the areas to the drop down.

Based on the above behavior this appears to have something to do with the way the caching is done for areas.  It should be compared to what is being done for the crops which are not exhibiting the same behavior.

----

<a href="https://github.com/braughtg"><img src="https://avatars.githubusercontent.com/u/16962482?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [braughtg](https://github.com/braughtg)**
_Tuesday Jun 07, 2022 at 13:06 GMT_
_Originally opened as https://github.com/DickinsonCollege/FarmData2/issues/460_

**Comment by braughtg** [comment]
Confirmed that this is related to the caching of the areas in the local storage.  When the areas are requested each time and not retrieved from cache there is no duplication.

----

<a href="https://github.com/braughtg"><img src="https://avatars.githubusercontent.com/u/16962482?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [braughtg](https://github.com/braughtg)**
_Tuesday Jun 07, 2022 at 13:16 GMT_

**Comment by braughtg** [comment]
Issue is that the call to getAllPages appends new responses to the provided array, it does not clear the array. Thus, when the cached version of the area response is used, the subsequent call to the API to check for updates adds to the response, it does not replace the response.

----

<a href="https://github.com/braughtg"><img src="https://avatars.githubusercontent.com/u/16962482?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [braughtg](https://github.com/braughtg)**
_Tuesday Jun 07, 2022 at 13:25 GMT_

**Comment by Sdaewa** [comment]
Hi there, can I work on this one?

**Comment by braughtg** [comment]
Hi @Sdaewa, This particular repository was created specifically for a college course, so I am not accepting PRs on it outside of the class. If you are interested in the FarmData2 project specifically the main project at (https://github.com/DickinsonCollege/FarmData2) and is open to contributions.  Feel free to check it out and connect there.
